"""Add plans and limits

Revision ID: 095e4ccd58ec
Revises: 3d4bbcc923f8
Create Date: 2025-03-12 08:40:07.194822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from src.users.models import Plans

# revision identifiers, used by Alembic.
revision: str = '095e4ccd58ec'
down_revision: Union[str, None] = '3d4bbcc923f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    plans_enum = postgresql.ENUM(Plans, name="plans")
    plans_enum.create(op.get_bind(), checkfirst=True)  # Создаем Enum тип

    op.add_column('users', sa.Column('plan', sa.Enum(Plans, name='plans'), nullable=False))
    op.add_column('users', sa.Column('message_length_limit', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('message_count_limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'message_count_limit')
    op.drop_column('users', 'message_length_limit')
    op.drop_column('users', 'plan')

    plans_enum = postgresql.ENUM(Plans, name="plans")
    plans_enum.drop(op.get_bind(), checkfirst=True)
