"""Add plan to transactions model

Revision ID: 1ee71b7a3d96
Revises: fe263f8a9c05
Create Date: 2025-03-12 18:22:13.201736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee71b7a3d96'
down_revision: Union[str, None] = 'fe263f8a9c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('plan', sa.Enum('default', 'premium', 'business', name='plans'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'plan')
    # ### end Alembic commands ###
