"""Add user_tokens_id to user model and fill with uuid4

Revision ID: 537ead03209d
Revises: 1ee71b7a3d96
Create Date: 2025-03-13 15:49:19.969511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid  # Импортируем uuid

# revision identifiers, used by Alembic.
revision: str = '537ead03209d'
down_revision: Union[str, None] = '1ee71b7a3d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_tokens_id', sa.UUID(), nullable=True))

    conn = op.get_bind()
    conn.execute(sa.text("UPDATE users SET user_tokens_id = gen_random_uuid() WHERE user_tokens_id IS NULL"))

    op.alter_column('users', 'user_tokens_id', nullable=False)

    op.create_index('ix_users_user_tokens_id', 'users', ['user_tokens_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_user_tokens_id', table_name='users')
    op.drop_column('users', 'user_tokens_id')
    # ### end Alembic commands ###
