"""Add new column to user model

Revision ID: a4b20bb1537b
Revises: b7f7f2cea542
Create Date: 2025-03-16 12:47:39.772111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a4b20bb1537b'
down_revision: Union[str, None] = 'b7f7f2cea542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan_purchase_date', sa.Date(), nullable=True))

    conn = op.get_bind()
    conn.execute(sa.text("UPDATE users SET plan_purchase_date = CURRENT_DATE WHERE plan_purchase_date IS NULL"))

    op.alter_column('users', 'plan_purchase_date', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan_purchase_date')
    # ### end Alembic commands ###
