"""Add available message field to user model

Revision ID: cb4f2ed98dcd
Revises: 49808b520b92
Create Date: 2025-03-14 10:14:55.363249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.users.models import plan_settings, Plans

# revision identifiers, used by Alembic.
revision: str = 'cb4f2ed98dcd'
down_revision: Union[str, None] = '49808b520b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get the default count limit
    default_count_limit = plan_settings[Plans.default.value]["count_limit"]

    op.add_column('users', sa.Column(
        'available_message_count', sa.Integer(), nullable=False, server_default=str(default_count_limit)))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'available_message_count')
