"""Add feedback model

Revision ID: ddb46ecb8a1f
Revises: a4b20bb1537b
Create Date: 2025-04-07 14:00:19.930225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb46ecb8a1f'
down_revision: Union[str, None] = 'a4b20bb1537b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the foreign key constraint
    op.drop_constraint('feedbacks_user_email_fkey', 'feedbacks', type_='foreignkey')

    # Then alter the column type
    op.alter_column('feedbacks', 'user_email',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)

    # Finally create the new foreign key constraint
    op.create_foreign_key(None, 'feedbacks', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the email-based foreign key
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')

    # Change the column back to UUID
    op.alter_column('feedbacks', 'user_email',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)

    # Recreate the original id-based foreign key
    op.create_foreign_key('feedbacks_user_email_fkey', 'feedbacks', 'users', ['user_email'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###