"""Add feedback model

Revision ID: fafaf1288acd
Revises: a4b20bb1537b
Create Date: 2025-04-07 09:44:26.158265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fafaf1288acd'
down_revision: Union[str, None] = 'a4b20bb1537b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(length=10000), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
