"""fix types in transaction model

Revision ID: fe263f8a9c05
Revises: 7975665d30ef
Create Date: 2025-03-12 09:31:29.351923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fe263f8a9c05'
down_revision: Union[str, None] = '7975665d30ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'transactions', 'amount',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=False,
        postgresql_using='amount::double precision'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'transactions', 'amount',
        existing_type=sa.Float(),
        type_=sa.Float(),  # Исправлено на sa.Float()
        existing_nullable=False,
        postgresql_using='amount::varchar'
    )
    # ### end Alembic commands ###
